// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCykuqsQuDyyg-8RBZAkpc9lrxzmkMFmQ8',
    appId: '1:338607451081:web:12d0aea0215924f8029618',
    messagingSenderId: '338607451081',
    projectId: 'todolist-63f19',
    authDomain: 'todolist-63f19.firebaseapp.com',
    storageBucket: 'todolist-63f19.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC6-rd_ad1xheYtGn9zXDsCEltjCLPaSwI',
    appId: '1:338607451081:android:2825633faea2af11029618',
    messagingSenderId: '338607451081',
    projectId: 'todolist-63f19',
    storageBucket: 'todolist-63f19.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCg7erk4z0fecudkW3Zc4vI_OxZS14fBg4',
    appId: '1:338607451081:ios:0b1676896f8f7cf4029618',
    messagingSenderId: '338607451081',
    projectId: 'todolist-63f19',
    storageBucket: 'todolist-63f19.firebasestorage.app',
    iosBundleId: 'com.example.myApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCg7erk4z0fecudkW3Zc4vI_OxZS14fBg4',
    appId: '1:338607451081:ios:0b1676896f8f7cf4029618',
    messagingSenderId: '338607451081',
    projectId: 'todolist-63f19',
    storageBucket: 'todolist-63f19.firebasestorage.app',
    iosBundleId: 'com.example.myApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCykuqsQuDyyg-8RBZAkpc9lrxzmkMFmQ8',
    appId: '1:338607451081:web:eb0bed7026c5a3ec029618',
    messagingSenderId: '338607451081',
    projectId: 'todolist-63f19',
    authDomain: 'todolist-63f19.firebaseapp.com',
    storageBucket: 'todolist-63f19.firebasestorage.app',
  );
}
